---
- hosts: all
  remote_user: vagrant
  become: yes
  become_user: root
  vars:
    of_version: of_v0.10.1_linuxarmv6l_release
    image: 2018-11-13-raspbian-stretch-lite.img
    # offset_boot: 4194304
    # offset_root: 7897874432
    offset_boot: 4194304
    offset_root: 50331648

  gather_facts: False
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: # aka gather_facts

  tasks:
    - apt: upgrade=dist update_cache=yes
    # - command: mkdir -p /opt/raspberrypi creates=/opt/raspberrypi
    - file: path=/opt/raspberrypi state=directory

    - apt: name=nfs-kernel-server
    - lineinfile: dest=/etc/exports line="/opt/raspberrypi/root 10.0.0.0/24(rw,sync,no_root_squash,no_subtree_check)"

    - lineinfile: dest=/etc/cron.d/opt_raspberrypi_root line="* * * * * root /bin/mount /opt/raspberrypi/root" create=yes

    # - service: name=nfs-kernel-server state=restarted

    - apt: name=build-essential
    - apt: name=pkg-config
    - apt: name=git
    - apt: name=ccache
    - apt: name=python-pip
    - apt: name=python-pip
    - apt: name=python-dev
    - apt: name=unzip
    - apt: name=gawk
    - apt: name=libudev-dev
    - apt: name=bison
    - apt: name=exfat-fuse
    - apt: name=exfat-utils

    - apt: name=sshpass
    - apt: name=kpartx

    - pip: name=ansible
    - pip: name=paramiko
    - pip: name=PyYAML
    - pip: name=jinja2
    - pip: name=httplib2

    # - apt: name=tinyproxy
    # - lineinfile: dest="/etc/tinyproxy.conf" line="Allow 10.0.0.0/8"
    # - service: name=tinyproxy state=restarted

    - file: path=/opt/raspberrypi/boot state=directory
    - file: path=/opt/raspberrypi/root state=directory

# sudo add-apt-repository ppa:ricotz/testing
# sudo apt-get update
# sudo apt-get install libcairo2-dev
# sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
# sudo apt-get install libglew-dev
# sudo apt-get install alsa-utils
# sudo apt-get install alsa
# sudo apt-get install libmpg123-dev
# sudo apt-get install libgtk2.0-dev
# sudo apt install libasound2-dev
# sudo apt-get install libpulse-dev
# sudo apt-get install libssl-dev
# sudo apt-get install portaudio19-dev
# sudo apt-get install libalut-dev
# sudo apt-get install libgstreamer1.0-0
# sudo apt-get install gstreamer1.0-plugins-base gstreamer1.0-plugins-good
# sudo apt-get install gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly
# sudo apt-get install gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools
# sudo apt-get install libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev
# sudo apt-get install libfontconfig1-dev libfreetype6-dev libpng-dev
# sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev
# sudo apt-get install libgstreamer-plugins-base1.0-dev


    - copy: src=2018-11-13-raspbian-stretch-lite.img dest=/home/vagrant/ mode=0755
    # - mount: src="/vagrant/{{image}}" name="/opt/raspberrypi/boot" fstype="vfat"  opts="loop,offset={{offset_boot}},auto,sizelimit=29360128" state="mounted"
    # - command: losetup -d /dev/loop0 /vagrant/{{image}}
    - command: kpartx -a -v /home/vagrant/2018-11-13-raspbian-stretch-lite.img
    - mount: src="/dev/mapper/loop0p1" name="/opt/raspberrypi/boot" fstype="vfat"   state="mounted"
    - mount: src="/dev/mapper/loop0p2" name="/opt/raspberrypi/root" fstype="ext4"   state="mounted"
    # - mount: src="home/vagrant/{{image}}" name="/opt/raspberrypi/boot" fstype="auto"  opts="loop,offset={{offset_boot}}" state="mounted"
    # - mount: src="home/vagrant/{{image}}" name="/opt/raspberrypi/root" fstype="auto"  opts="loop,offset={{offset_root}}" state="mounted"
    # - lineinfile: dest=/etc/rc.local line="mount /opt/raspberrypi/root" insertbefore="exit 0"
    # - lineinfile: dest=/etc/rc.local line="mount /opt/raspberrypi/boot" insertbefore="exit 0"

    # the pi is unbootable unless it is told not to mount the root filesystem from the card!
    - lineinfile: dest=/opt/raspberrypi/root/etc/fstab regexp="^\/dev\/mmcblk0p2" state="absent"
    - replace: dest=/opt/raspberrypi/boot/cmdline.txt regexp="rootwait$" replace="dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline root=/dev/nfs rootfstype=nfs nfsroot=10.0.0.1:/opt/raspberrypi/root,udp,vers=3 rw fsck.repair=no rootwait ip=10.0.0.101:10.0.0.1:10.0.0.1:255.255.255.0:rpi:eth0:off smsc95xx.turbo_mode=N" backup=no

    # build helpies
    - file: path=/opt/RPI_BUILD_ROOT state=directory
    - file: src=/opt/raspberrypi/root/etc dest=/opt/RPI_BUILD_ROOT/etc state=link
    - file: src=/opt/raspberrypi/root/lib dest=/opt/RPI_BUILD_ROOT/lib state=link
    - file: src=/opt/raspberrypi/root/opt dest=/opt/RPI_BUILD_ROOT/opt state=link
    - command: rsync -avz /opt/raspberrypi/root/usr/ /opt/RPI_BUILD_ROOT/usr


    - file: path=/tmp/CROSS_BUILD_TOOLS state=directory
    - copy: src=build_cross_gcc.sh dest=/tmp/CROSS_BUILD_TOOLS/build_cross_gcc.sh mode=0744
    - shell: /tmp/CROSS_BUILD_TOOLS/build_cross_gcc.sh chdir=/tmp/CROSS_BUILD_TOOLS creates=/opt/cross/bin/arm-linux-gnueabihf

    - shell: 
        cmd: rm libanl.so libBrokenLocale.so libcidn.so libcrypt.so libdbus-1.so libdl.so libexpat.so libglib-2.0.so liblzma.so libm.so libmnl.so libnsl.so libnss_compat.so libnss_dns.so libnss_files.so libnss_hesiod.so libnss_nisplus.so libnss_nis.so libpcre.so  libresolv.so librt.so libthread_db.so libusb-1.0.so libutil.so libuuid.so libz.so
        chdir: /opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf

    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libanl.so.1           dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libanl.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libBrokenLocale.so.1  dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libBrokenLocale.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libcidn.so.1          dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libcidn.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libcrypt.so.1         dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libcrypt.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libdbus-1.so.3.14.15   dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libdbus-1.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libdl.so.2            dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libdl.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libexpat.so.1.6.2     dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libexpat.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libglib-2.0.so.0      dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libglib-2.0.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/liblzma.so.5.2.2      dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/liblzma.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libm.so.6             dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libm.so state=link
    # - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libmn1.so.1           dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libmn1.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libnsl.so.1           dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libnsl.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libnss_compat.so.2    dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libnss_compat.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libnss_dns.so.2       dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libnss_dns.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libnss_files.so.2     dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libnss_files.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libnss_hesiod.so.2    dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libnss_hesiod.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libnss_nisplus.so.2   dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libnss_nisplus.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libnss_nis.so.2       dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libnss_nis.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libpcre.so.3          dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libpcre.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libresolv.so.2        dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libresolv.so state=link
    # - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/librt.so.2            dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/librt.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libthread_db.so.1     dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libthread_db.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libusb-1.0.so.0.1.0   dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libusb-1.0.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libutil.so.1          dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libutil.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libuuid.so.1.3.0          dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libuuid.so state=link
    - file: src=/opt/raspberrypi/root/lib/arm-linux-gnueabihf/libz.so.1.2.8         dest=/opt/raspberrypi/root/usr/lib/arm-linux-gnueabihf/libz.so state=link

      #environmental vars
    - lineinfile: dest="/home/vagrant/.profile" line="export GCC_PREFIX=arm-linux-gnueabihf"
    - lineinfile: dest="/home/vagrant/.profile" line="export GST_VERSION=1.0"
    - lineinfile: dest="/home/vagrant/.profile" line="export RPI_ROOT=/opt/raspberrypi/root"
    #- lineinfile: dest="/home/vagrant/.profile" line="export RPI_BUILD_ROOT=/opt/RPI_BUILD_ROOT"
    - lineinfile: dest="/home/vagrant/.profile" line="export TOOLCHAIN_ROOT=/opt/cross/bin"
    - lineinfile: dest="/home/vagrant/.profile" line="export PLATFORM_OS=Linux"
    - lineinfile: dest="/home/vagrant/.profile" line="export PLATFORM_ARCH=armv6l"
    - lineinfile: dest="/home/vagrant/.profile" line="export PKG_CONFIG_PATH=${RPI_ROOT}/usr/lib/${GCC_PREFIX}/pkgconfig:${RPI_ROOT}/usr/lib/pkgconfig:${RPI_ROOT}/usr/share/pkgconfig"
    - lineinfile: dest="/home/vagrant/.profile" line="export CXX=${TOOLCHAIN_ROOT}/${GCC_PREFIX}-g++"
    - lineinfile: dest="/home/vagrant/.profile" line="export CC=${TOOLCHAIN_ROOT}/${GCC_PREFIX}-gcc"
    - lineinfile: dest="/home/vagrant/.profile" line="export AR=${TOOLCHAIN_ROOT}/${GCC_PREFIX}-ar"
    - lineinfile: dest="/home/vagrant/.profile" line="export LD=${TOOLCHAIN_ROOT}/${GCC_PREFIX}-ld"
    
    #OF
    # - unarchive: src={{of_version}}.tar.gz dest=/opt/raspberrypi/root/opt creates=/opt/raspberrypi/root/opt/{{of_version}}
    - shell: 
        cmd: git clone -b patch-release https://github.com/openframeworks/openFrameworks.git {{of_version}}
        chdir: /opt/raspberrypi/root/opt/
    - file: src={{of_version}} dest=/opt/raspberrypi/root/opt/openframeworks state=link
    - file: src=/opt/raspberrypi/root/opt/openframeworks dest=/opt/openframeworks state=link
    - command: chown -R vagrant /opt/raspberrypi/root/opt/{{of_version}}
    - command: sudo /opt/openframeworks/scripts/linux/download_libs.sh
    - command: sudo /opt/openframeworks/scripts/linux/debian/install_dependencies.sh
    - command: sudo /opt/openframeworks/scripts/linux/debian/install_codecs.sh
    - command: sudo /opt/openframeworks/scripts/ci/linuxarmv6l/install.sh
    - command: sudo openFrameworks/scripts/linux/compileOF.sh



  handlers:

